### ISSUE TITLE
Cannot build the docs because of dead links

### ISSUE THREAD

**Issue by nhedger** [hybridly/hybridly#83]
### Describe the bug

I cannot build the docs locally (apparently, the CI also fails) because there are dead links in the documentation.

```
(!) Found dead link ./../api/vite/layout in file guide/comparison-with-inertia.md
(!) Found dead link ./../api/vue/index in file guide/hooks.md
(!) Found dead link ./../api/vite/layout in file guide/pages-and-layouts.md
(!) Found dead link ./../api/vite/layout in file guide/visual-studio-code.md
```

It looks like the following paths do not exist anymore.

- `docs/api/vite`
- `docs/api/vue`

### Reproduction

https://github.com/hybridly/hybridly

### Steps to reproduce

1. Attempt to build the docs with `pnpm docs:build`

### System information

```bash
System:
    OS: macOS 13.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 2.76 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/Library/Caches/fnm_multishells/36059_1687446196824/bin/node
    npm: 8.19.3 - ~/Library/Caches/fnm_multishells/36059_1687446196824/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Edge: 114.0.1823.51
    Safari: 16.4
  npmPackages:
    @hybridly/core: workspace:* => 0.4.0 
    @hybridly/progress-plugin: workspace:* => 0.4.0 
    @hybridly/utils: workspace:* => 0.4.0 
    @hybridly/vite: workspace:* => 0.4.0 
    @hybridly/vue: workspace:* => 0.4.0 
    hybridly: workspace:* => 0.4.0
```

### Used package manager

pnpm

### Logs

<details>
<summary>Build log</summary>

```shell
~/Code/hybridly pnpm docs:build

> @0.4.0 docs:build /Users/nicolas/Code/hybridly
> vitepress build docs


  vitepress v1.0.0-beta.1

⠧ building client + server bundles...
The language 'gitignore' is not loaded, falling back to 'txt' for syntax highlighting.
⠴ building client + server bundles...

(!) Found dead link ./../api/vite/layout in file guide/comparison-with-inertia.md
(!) Found dead link ./../api/vue/index in file guide/hooks.md
(!) Found dead link ./../api/vite/layout in file guide/pages-and-layouts.md
(!) Found dead link ./../api/vite/layout in file guide/visual-studio-code.md

If this is expected, you can disable this check via config. Refer: https://vitepress.dev/reference/site-config#ignoredeadlinks

[vitepress] 4 dead link(s) found.
✖ building client + server bundles...
build error:
Error: 4 dead link(s) found.
    at Object.renderStart (file:///Users/nicolas/Code/hybridly/node_modules/vitepress/dist/node/serve-d5608de4.js:37067:15)
    at file:///Users/nicolas/Code/hybridly/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:24899:40
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async PluginDriver.hookParallel (file:///Users/nicolas/Code/hybridly/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:24827:9)
    at async Bundle.generate (file:///Users/nicolas/Code/hybridly/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:17654:13)
    at async file:///Users/nicolas/Code/hybridly/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:26132:27
    at async catchUnfinishedHookActions (file:///Users/nicolas/Code/hybridly/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:25265:16)
 ELIFECYCLE  Command failed with exit code 1.
```

</details

### Validations

- [X] Read the [docs](https://hybridly.dev).
- [X] Check that there isn't [already an issue](https://github.com/hybridly/hybridly/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Hybridly issue and not an issue related to something else (Vite, Vue...). For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A, join our [Discord server](https://discord.gg/uZ8eC7kRFV).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by innocenzi** [comment]
Oh thanks, I might have removed some pages that shouldn't have been removed, I'll fix that soon

**Comment by nhedger** [comment]
```
git log -n 1 --pretty=format:%h -- docs/api/vue
```

It looks like it was modified in commit 203b3f1.

**Comment by innocenzi** [comment]
Yes, the pages were rightfully deleted but the links to those were not. Fixed, thank you!

**Comment by nhedger** [comment]
Thank you @innocenzi!
